### ISSUE TITLE
Meteor and Fuel overlapping (Enhancement)

### ISSUE THREAD

**Issue by JoryFarice** [Bloomfield-SP16-CAT308A/ShedInSpace#10]
This is more of an enhancement than a bug, but there are times where the meteors and the fuel pick ups overlap which makes it impossible to grab the fuel. This also happens with bombs.

**Comment by JohnLandi** [comment]
Going to look into making it only spawn one or the other on the same timer. It should fix this and make gameplay better.

**Comment by JohnLandi** [comment]
Fixed
