### ISSUE TITLE
Different Types of Stars

### ISSUE THREAD

**Issue by Rjimenez813** [Bloomfield-SP16-CAT308A/ShedInSpace#15]
## Enhancement

So a nice idea for a starry background could be completely black (or blue) and have dots and + shaped stars all around. It can have multiple layers too where the ones in the back move slower than the ones in the front. It would look cool as shit and... your background doesn't look cool as shit atm. So do that.

**Comment by JohnLandi** [comment]
Going to have it like the game you showed me for this to make them smaller and vary in size.

**Comment by JohnLandi** [comment]
Fixed
