### ISSUE TITLE
score, and level mechanics

### ISSUE THREAD

**Issue by NeoChrisOmega** [Bloomfield-SP16-CAT308A/ShedInSpace#17]
I feel as if the game could use some more levels, or at least a different way of using the score to keep people interested

## Steps to Reproduce
1. extract on android
2. play game
3. get hit after building a score

## Expected Results
there to be a next level, or visual event happen when I get hit

## Actual Results
score just goes to 0, keeping the high score

**Comment by JohnLandi** [comment]
The plan is to only have one level.
