### ISSUE TITLE
The asteroid is treated as fuel

### ISSUE THREAD

**Issue by UNDERGND24** [Bloomfield-SP16-CAT308A/ShedInSpace#21]
Steps to reproduce:

1. Launch app

2. Wait for asteroid

3. Let asteroid hit you and look at the fuel count

Expected outcome:

Player will die or take damage.

Actual outcome:

Player receives more fuel and doesn't get hurt.

**Comment by UNDERGND24** [comment]
*As a side note I played the version of the game that was on the android devices in the closet in the CAT Lab.

**Comment by JohnLandi** [comment]
It resets because the player is supposed to die and the age resets.
